server:
  port: 8100
spring:
  profiles:
    include: common
  application:
    name: exam-api # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 服务发现

  # 数据源
  datasource:
    username: ${constant.mysql.username}
    password: ${constant.mysql.password}
    url: jdbc:mysql://127.0.0.1:3306/xzsss?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
  redis:
    port: 6379
    host: 127.0.0.1

# 修改默认日志级别，以输出Feign调用日志
logging:
  level:
    com.gdpu.core.feign: debug

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
